name: CI

on: [push]

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: rubymn2_user
          POSTGRES_PASSWORD: rubymn2_password
          POSTGRES_DB: rubymn2

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby and run bundle install
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true
      - name: Show Ruby version
        run: ruby -v
      - name: Prepare database and run tests
        env:
          RAILS_ENV: test
          POSTGRES_USER=agent007
          POSTGRES_PASSWORD=BondJamesBond
          POSTGRES_DB=rubymn2
        run: | 
          bundle exec rake db:create db:migrate db:test:prepare
          bundle exec rake test
