name: CI

on: [push]

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: rubymn2_user
          POSTGRES_PASSWORD: rubymn2_password
          POSTGRES_DB: rubymn2

    steps:
      - uses: actions/checkout@v1
      - name: bundle install
        run: bundle install
      - name: Run tests
        env:
          RAILS_ENV: test
        run: bundle exec rake db:create db:migrate db:test:prepare
