name: CI

on: [push]

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: agent007
          POSTGRES_PASSWORD: BondJamesBond
          POSTGRES_DB: rubymn2_db

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby and run bundle install
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true
      - name: Show Ruby version
        run: ruby -v
      - name: Prepare database and run tests
        env:
          # RAILS_ENV=test
          # POSTGRES_HOST=database
          # POSTGRES_DB=rubymn2_db
          # POSTGRES_USER=agent007
        run:
          bundle exec rake db:create db:migrate db:test:prepare
          bundle exec rake test
